version: "3.5"
services:
  pg:
    image: postgres:12.1
#    user: postgres
#    user: $(id -u):$(id -g)
#    user: ${PGUSERID}
    restart: unless-stopped
    env_file: .env
    shm_size: '256mb'
    expose:
      - 5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
    depends_on:
      - pg
#    user: "node"
    user: ${APIUSERID}
    restart: unless-stopped
    env_file: .env
    ports:
      - ${APIPORT}:3000
    volumes:
      - ./certs:/home/node/app/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1s
      timeout: 3s
      retries: 30
    command: ["npm", "run", "start"]
